# build_content.sh  major_current.minor_current.build_current
# 
# script for building new update archive
# of given configuration. You need a bash
# shell environment, tar, gzip, md5sum, sed, xargs
# e.g. a linux OS or cygwin installed on 
# your PC to make it work.
# 
# Make sure to compile project with the macro
# try to load from PC deactivated
#
# 2006 Peiker acustic

# Imports variable n (archive counter) 


rm -R -f content

mkdir content
cd content

# extracts version numbers
# version=${1//./' '}
# version_arr=($version)
# major_ver=${version_arr[0]}
# minor_ver=${version_arr[0]}
# build_ver=${version_arr[0]}

major_ver=$(echo $1 | sed 's/\([0-9][0-9]\)\.\([0-9][0-9]\)\.\([0-9][0-9]\)/\1/')
minor_ver=$(echo $1 | sed 's/\([0-9][0-9]\)\.\([0-9][0-9]\)\.\([0-9][0-9]\)/\2/')
build_ver=$(echo $1 | sed 's/\([0-9][0-9]\)\.\([0-9][0-9]\)\.\([0-9][0-9]\)/\3/')

# integrate VBI software 
cp ../hc12_images/hc12ft.txt		   hc12ft.txt
cp ../hc12_images/hc12hs.txt	   	   hc12hs.txt


tar cvf ../content.tar *
cd ..
rm -R -f content

echo "# update script for installing the BTHFCK2 kernel file and reflashing HC12" > command.sh
echo -n "# generated by build script on " >> command.sh
date >> command.sh
echo >> command.sh

echo "# unpack archive for software update" >> command.sh
echo "tar xvf arv$n/content.tar" >> command.sh
echo >> command.sh

echo "#reflash HC12" >> command.sh
echo "vbi_reflash 02202006" >> command.sh
echo >> command.sh

echo "# update build version number" >> command.sh
echo "# this is still not implemented" >> command.sh
hc12_ver=$(cat ./hc12_images/version | sed 's/\([0-9][0-9]\)\(.*\)/\1/')
echo -n "# set_hc12_version b$hc12_ver" >> command.sh
echo >> command.sh

echo "# clean up temporary files" >> command.sh
echo "rm /hc12ft.txt" >> command.sh
echo "rm /hc12hs.txt" >> command.sh
echo >> command.sh


